### PR TITLE
Remove non mvp content

### PR DESCRIPTION
**Pull request by Woolfe-Glitch**

### CODE REVIEW

**Review by garrettdigital — CHANGES_REQUESTED** [review]
There seems to be a lot of other changes rather than just removing content. Was this intentional or is this a branch conflict issue?

**Comment by Woolfe-Glitch** [comment]
> There seems to be a lot of other changes rather than just removing content. Was this intentional or is this a branch conflict issue?

It was intentional. The sections were removed fully.

**Comment by garrettdigital** [comment]
> There seems to be a lot of other changes rather than just removing content. Was this intentional or is this a branch conflict issue?

Follow up with Conner to try and fix the merge conflicts.

**Comment by Woolfe-Glitch** [comment]
> 
> 
> > There seems to be a lot of other changes rather than just removing content. Was this intentional or is this a branch conflict issue?
> 
> Follow up with Conner to try and fix the merge conflicts.

This has been done. Merge Conflicts fixed.

**Review by garrettdigital — APPROVED** [review]
Looks good.

**Pull request merged**
